version: "3.7"

services:
  datascience:
    stdin_open: true
    tty: true
    container_name: datascience
    build:
      context: .
      dockerfile: ./docker/datascience.dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - "8899:8899"
    command: jupyter notebook --port=8899 --ip=0.0.0.0 --no-browser --allow-root
